# datasets
data_path: "../../../data/external"
seed: 1

# optimizer
optimizer: "Adagrad"  # Adagrad
lr: 0.01

# reconstruction loss
rec_loss: "binary_cross_entropy"

# learning rate
batch_size: 100  # 100
epochs: 5  # 100

# VAE architecture
input_dim: 784  # for the MNIST dataset
z_dim: 2  # 3
encoder_hidden_dim: 500  # 400
decoder_hidden_dim: 500

# beta vae
beta: 10.0

# activation functions
encoder_act_func: "tanh"
decoder_act_func: "tanh"
decoder_pred_func: "sigmoid"

# weights and biases logging
project: "vae_kingma"
wandb: False
group: "delete_me"
test_num_img: 10
save_model: False

# reloading
checkpoint_path: "../training/wandb/run-20201123_142645-nrubygd3/files/model_state.pt"
